import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Image from "next/image";
import pic from "./pic/libBg.jpg";

export const metadata: Metadata = {
  title: "Next-Doc-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="bg-neutral-800 h-full min-h-[calc(100vh-2.3rem)] flex justify-center relative">
          <Image
            src={pic}
            alt="Bild på ett bibliotek"
            className="w-full h-full object-cover absolute mix-blend-overlay"
          />
          <div className="w-full mt-3 max-w-screen-lg flex justify-center z-10">
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
